[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12

decorations = "Buttonless"

opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 14

# normal.family = "Iosevka Nerd Font"
#size = 16

