format = """$directory$git_branch$git_status """

[directory]
style = "bold blue"
format = "[$path]($style) "

[git_branch]
style = "bold purple"
format = "[$branch]($style) "

[git_status]
style = "purple"
format = "[$all_status]($style)"

[nodejs]
disabled = true

